### PR TITLE
Refactor package installs

### PR DESCRIPTION
**Pull request by sjpb**
This changes how package installs are done which allows separation (via tags) of install and configuration phases. This makes use of this role much more flexible.

Master branch has 3x main playbooks:
- `compute` and `control`, which a) set the relevant slurm service and b) install appropriate packages
- `runtime`, used on both node types, which installs more packages and does the actual configuration of slurm
These run sequentially, which is slow as e.g. control skips all the compute package installs.

This PR switches this around and builds a node-type-specific package (compute or control packages, + runtime packages + user-supplied packages). This also makes installs faster as they happen on all nodes in parallel.

This also fixes changes to the molecule package used for tests so travis tests run/pass.

### CODE REVIEW

**Comment by oneswig** [comment]
Hi @sjpb looks good to me.  I wanted to check you've covered the case for (eg) a login node which is neither control nor batch.  It looks like it is covered but wanted to be sure.

Also, is there a convention for why some variables are prefixed `openhpc_` and others `ohpc_`?

**Comment by sjpb** [comment]
Thanks @oneswig. Yes the login node case should be covered - in current `master` that is what you get AFAIK if you set `runtime` but not `batch` or `control` - and that logic hasn't changed, just moved around.

I thought I was following your convention with `openhpc_` being "public" role variables and `ohpc_` ones being "private" e.g. defaults etc where it's not appropriate for them to be set when calling the role.

**Comment by oneswig** [comment]
Thanks Steve - I thought that was the case but couldn't remember...

**Review by oneswig — APPROVED** [review]
LGTM, thanks @sjpb

**Pull request merged**
