### PR TITLE
CI Workaround: Failed to parse bus message: Invalid argument

### PR DESCRIPTION
**Pull request by jovial**
For rationale, please see comment in change.

### CODE REVIEW

**Comment by jovial** [comment]
Clarification: It is the systemd in the containers that is too old to handle the capabilities present in the host kernel.

**Comment by jovial** [comment]
CI failure was: `fatal: [testohpc-grp2-0]: FAILED! => {"changed": false, "msg": "Failure downloading http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm, Request failed: <urlopen error timed out>"}` re-running jobs.

**Comment by jovial** [comment]
Hmm, hit pip download issues this time:
```
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```
and a [genuine failure on test12:](https://github.com/stackhpc/ansible-role-openhpc/pull/110/checks?check_run_id=3075724084#step:8:593)
```
  TASK [assert] ******************************************************************
  fatal: [testohpc-login-0]: FAILED! => {
      "assertion": "(jobid + '|0|wrap|compute|2|testohpc-compute-[0-1]|COMPLETED') in sacct.stdout",
      "changed": false,
      "evaluated_to": false,
      "msg": "Didn't find expected output for 2 in sacct output: "
  }
  ```

**Comment by sjpb** [comment]
Weird test12 has passed now then?

**Comment by jovial** [comment]
> Weird test12 has passed now then?

Yep, I guess we just got unlucky on that run!

**Review by sjpb — APPROVED** [review]
LGTM, I've added #111 as a reminder that we probably want to bump this at some point.

**Pull request merged**
